apiVersion: v1
kind: Service
metadata:
  name: person-service-rest
  labels:
    app: person
    svc: rest
spec:
  type: NodePort
  selector:
    app: person
    svc: rest
  ports:
  - name: rest
    port: 5000
    targetPort: 5000
    nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: person-service-grpc
  labels:
    app: person
    svc: grpc
spec:
  type: ClusterIP
  selector:
    app: person
    svc: grpc
  ports:
  - name: grpc
    port: 5005
    targetPort: 5005
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: person
    svc: rest
  name: person-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: person
      svc: rest
  template:
    metadata:
      labels:
        app: person
        svc: rest
    spec:
      containers:
      - image: amit2555/udaconnect-person
        name: person-rest
        imagePullPolicy: Always
        ports:
        - name: rest
          containerPort: 5000
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: person
    svc: grpc
  name: person-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: person
      svc: grpc
  template:
    metadata:
      labels:
        app: person
        svc: grpc
    spec:
      containers:
      - image: amit2555/udaconnect-person
        name: person-grpc
        command: ["python", "grpc_server.py"]
        imagePullPolicy: Always
        ports:
        - name: grpc
          containerPort: 5005
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT

