apiVersion: v1
kind: Pod
metadata:
  labels:
    app: location-consume
  name: location-consume
spec:
  containers:
  - image: amit2555/udaconnect-location-consume
    name: location-consume
    tty: true
    imagePullPolicy: Always
    env:
    - name: DB_USERNAME
      valueFrom:
        configMapKeyRef:
          name: db-env
          key: DB_USERNAME
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: DB_PASSWORD
    - name: DB_NAME
      valueFrom:
        configMapKeyRef:
          name: db-env
          key: DB_NAME
    - name: DB_HOST
      valueFrom:
        configMapKeyRef:
          name: db-env
          key: DB_HOST
    - name: DB_PORT
      valueFrom:
        configMapKeyRef:
          name: db-env
          key: DB_PORT
