apiVersion: v1
kind: Service
metadata:
  name: connection-service-rest
  labels:
    app: connection
    svc: rest
spec:
  type: NodePort
  selector:
    app: connection
  ports:
  - name: rest
    port: 5000
    targetPort: 5000
    nodePort: 30002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: connection
  name: connection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connection
  template:
    metadata:
      labels:
        app: connection
    spec:
      containers:
      - image: amit2555/udaconnect-connection
        name: connection-service
        imagePullPolicy: Always
        ports:
        - name: rest
          containerPort: 5000
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT

