apiVersion: v1
kind: Service
metadata:
  name: location-process-service
  labels:
    app: location-process
    svc: rest
spec:
  type: NodePort
  selector:
    app: location-process
    svc: rest
  ports:
  - name: rest
    port: 5000
    targetPort: 5000
    nodePort: 30003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: location-process
    svc: rest
  name: location-process
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-process
      svc: rest
  template:
    metadata:
      labels:
        app: location-process
        svc: rest
    spec:
      containers:
      - image: amit2555/udaconnect-location-process
        name: location-process
        imagePullPolicy: Always
        ports:
        - name: rest
          containerPort: 5000
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
