name: Udaconnect - Package with Docker

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Dockerhub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build image and push PersonService to Dockerhub
      uses: docker/build-push-action@v2
      with:
        context: . 
        file: ./modules/01-person-service/Dockerfile
        platforms: linux/amd64
        push: true
        tags: amit2555/udaconnect-person:latest

    - name: Build image and push LocationProcessService to Dockerhub
      uses: docker/build-push-action@v2
      with:
        context: . 
        file: ./modules/02a-location-process-service/Dockerfile
        platforms: linux/amd64
        push: true
        tags: amit2555/udaconnect-location-process:latest

    - name: Build image and push LocationConsumeService to Dockerhub
      uses: docker/build-push-action@v2
      with:
        context: . 
        file: ./modules/02b-location-consume-service/Dockerfile
        platforms: linux/amd64
        push: true
        tags: amit2555/udaconnect-location-consume:latest

    - name: Build image and push ConnectionService to Dockerhub
      uses: docker/build-push-action@v2
      with:
        context: . 
        file: ./modules/03-connection-service/Dockerfile
        platforms: linux/amd64
        push: true
        tags: amit2555/udaconnect-connection:latest

    - name: Build image and push FrontendService to Dockerhub
      uses: docker/build-push-action@v2
      with:
        context: . 
        file: ./modules/04-frontend/Dockerfile
        platforms: linux/amd64
        push: true
        tags: amit2555/udaconnect-frontend:latest
